apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lz5sywczw-go 
  janus-idp.io/tekton: lz5sywczw-go
  backstage.io/kubernetes-id: lz5sywczw-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lz5sywczw-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml